
#  Copyright (C) 2018 University of Tuebingen
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, version 3.
#
#  This program is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program. If not, see <http://www.gnu.org/licenses/>.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FunctionalInput(object):

    def setupUi(self, FunctionalInput):
        FunctionalInput.setObjectName("FunctionalInput")
        FunctionalInput.resize(693, 570)
        FunctionalInput.setStyleSheet("")
        FunctionalInput.setFrameShape(QtWidgets.QFrame.NoFrame)
        FunctionalInput.setFrameShadow(QtWidgets.QFrame.Plain)
        FunctionalInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        FunctionalInput.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -1297, 672, 1867))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wid_initialStateVectorTitle = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_initialStateVectorTitle.sizePolicy().hasHeightForWidth())
        self.wid_initialStateVectorTitle.setSizePolicy(sizePolicy)
        self.wid_initialStateVectorTitle.setMinimumSize(QtCore.QSize(0, 70))
        self.wid_initialStateVectorTitle.setStyleSheet("background-color: white")
        self.wid_initialStateVectorTitle.setObjectName("wid_initialStateVectorTitle")
        self.la_initialStateVector = QtWidgets.QLabel(self.wid_initialStateVectorTitle)
        self.la_initialStateVector.setGeometry(QtCore.QRect(20, 10, 571, 60))
        self.la_initialStateVector.setMinimumSize(QtCore.QSize(0, 60))
        self.la_initialStateVector.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.la_initialStateVector.setFont(font)
        self.la_initialStateVector.setScaledContents(False)
        self.la_initialStateVector.setObjectName("la_initialStateVector")
        self.wid_initialStateVector_2 = QtWidgets.QWidget(self.wid_initialStateVectorTitle)
        self.wid_initialStateVector_2.setGeometry(QtCore.QRect(0, 77, 555, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_initialStateVector_2.sizePolicy().hasHeightForWidth())
        self.wid_initialStateVector_2.setSizePolicy(sizePolicy)
        self.wid_initialStateVector_2.setMinimumSize(QtCore.QSize(0, 70))
        self.wid_initialStateVector_2.setStyleSheet("background-color: white")
        self.wid_initialStateVector_2.setObjectName("wid_initialStateVector_2")
        self.verticalLayout.addWidget(self.wid_initialStateVectorTitle)
        self.wid_initialStateVector = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_initialStateVector.sizePolicy().hasHeightForWidth())
        self.wid_initialStateVector.setSizePolicy(sizePolicy)
        self.wid_initialStateVector.setMinimumSize(QtCore.QSize(0, 650))
        self.wid_initialStateVector.setStyleSheet("background-color: white")
        self.wid_initialStateVector.setObjectName("wid_initialStateVector")
        self.la_initialStateVector.raise_()
        self.verticalLayout.addWidget(self.wid_initialStateVector)
        self.wid_factorDistributionTitel = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_factorDistributionTitel.sizePolicy().hasHeightForWidth())
        self.wid_factorDistributionTitel.setSizePolicy(sizePolicy)
        self.wid_factorDistributionTitel.setMinimumSize(QtCore.QSize(0, 70))
        self.wid_factorDistributionTitel.setStyleSheet("background-color: white")
        self.wid_factorDistributionTitel.setObjectName("wid_factorDistributionTitel")
        self.la_factorDistribution = QtWidgets.QLabel(self.wid_factorDistributionTitel)
        self.la_factorDistribution.setGeometry(QtCore.QRect(20, 10, 571, 60))
        self.la_factorDistribution.setMinimumSize(QtCore.QSize(0, 60))
        self.la_factorDistribution.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.la_factorDistribution.setFont(font)
        self.la_factorDistribution.setScaledContents(False)
        self.la_factorDistribution.setObjectName("la_factorDistribution")
        self.verticalLayout.addWidget(self.wid_factorDistributionTitel)
        self.wid_factorDistribution = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_factorDistribution.sizePolicy().hasHeightForWidth())
        self.wid_factorDistribution.setSizePolicy(sizePolicy)
        self.wid_factorDistribution.setMinimumSize(QtCore.QSize(0, 650))
        self.wid_factorDistribution.setStyleSheet("background-color: white")
        self.wid_factorDistribution.setObjectName("wid_factorDistribution")
        self.verticalLayout.addWidget(self.wid_factorDistribution)
        self.wid_transitionFunctions = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_transitionFunctions.sizePolicy().hasHeightForWidth())
        self.wid_transitionFunctions.setSizePolicy(sizePolicy)
        self.wid_transitionFunctions.setMinimumSize(QtCore.QSize(0, 70))
        self.wid_transitionFunctions.setStyleSheet("background-color: white")
        self.wid_transitionFunctions.setObjectName("wid_transitionFunctions")
        self.la_transitionFunctions = QtWidgets.QLabel(self.wid_transitionFunctions)
        self.la_transitionFunctions.setGeometry(QtCore.QRect(20, 10, 571, 60))
        self.la_transitionFunctions.setMinimumSize(QtCore.QSize(0, 60))
        self.la_transitionFunctions.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.la_transitionFunctions.setFont(font)
        self.la_transitionFunctions.setScaledContents(False)
        self.la_transitionFunctions.setObjectName("la_transitionFunctions")
        self.verticalLayout.addWidget(self.wid_transitionFunctions)
        self.wid_transitionFunction = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_transitionFunction.sizePolicy().hasHeightForWidth())
        self.wid_transitionFunction.setSizePolicy(sizePolicy)
        self.wid_transitionFunction.setMinimumSize(QtCore.QSize(0, 300))
        self.wid_transitionFunction.setStyleSheet("background-color: white")
        self.wid_transitionFunction.setObjectName("wid_transitionFunction")
        self.verticalLayout.addWidget(self.wid_transitionFunction)
        self.wid_initialStateVectorTitle.raise_()
        self.wid_initialStateVector.raise_()
        self.la_factorDistribution.raise_()
        self.wid_factorDistribution.raise_()
        self.wid_factorDistributionTitel.raise_()
        self.wid_factorDistribution.raise_()
        self.wid_transitionFunctions.raise_()
        self.wid_transitionFunction.raise_()
        FunctionalInput.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(FunctionalInput)
        QtCore.QMetaObject.connectSlotsByName(FunctionalInput)

    def retranslateUi(self, FunctionalInput):
        _translate = QtCore.QCoreApplication.translate
        FunctionalInput.setWindowTitle(_translate("FunctionalInput", "ScrollArea"))
        self.la_initialStateVector.setText(_translate("FunctionalInput", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:400;\">Initial state distribution:</span></p></body></html>"))
        self.la_factorDistribution.setText(_translate("FunctionalInput", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:400;\">Factor distribution:</span></p></body></html>"))
        self.la_transitionFunctions.setText(_translate("FunctionalInput", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:400;\">Transition functions:</span></p></body></html>"))

