
#  Copyright (C) 2018 University of Tuebingen
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, version 3.
#
#  This program is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program. If not, see <http://www.gnu.org/licenses/>.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectTab(object):

    def setupUi(self, ProjectTab):
        ProjectTab.setObjectName("ProjectTab")
        ProjectTab.resize(1416, 894)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ProjectTab.sizePolicy().hasHeightForWidth())
        ProjectTab.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ProjectTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(ProjectTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(-1, 11, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_MC = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_MC.sizePolicy().hasHeightForWidth())
        self.label_MC.setSizePolicy(sizePolicy)
        self.label_MC.setMinimumSize(QtCore.QSize(120, 0))
        self.label_MC.setSizeIncrement(QtCore.QSize(34, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_MC.setFont(font)
        self.label_MC.setObjectName("label_MC")
        self.verticalLayout.addWidget(self.label_MC)
        self.frameInput = QtWidgets.QFrame(self.frame_2)
        self.frameInput.setObjectName("frameInput")
        self.layoutInput_2 = QtWidgets.QVBoxLayout(self.frameInput)
        self.layoutInput_2.setContentsMargins(-1, 0, -1, 5)
        self.layoutInput_2.setSpacing(8)
        self.layoutInput_2.setObjectName("layoutInput_2")
        self.tabWidget_inputVisualisation = QtWidgets.QTabWidget(self.frameInput)
        self.tabWidget_inputVisualisation.setObjectName("tabWidget_inputVisualisation")
        self.mc1 = QtWidgets.QWidget()
        self.mc1.setObjectName("mc1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mc1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.mc1)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_2)
        self.scrollArea.setStyleSheet("background-color: white")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.wid_scrollArea = QtWidgets.QWidget()
        self.wid_scrollArea.setGeometry(QtCore.QRect(0, 0, 577, 695))
        self.wid_scrollArea.setObjectName("wid_scrollArea")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.wid_scrollArea)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.wid_initialStateVectorTitle = QtWidgets.QWidget(self.wid_scrollArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_initialStateVectorTitle.sizePolicy().hasHeightForWidth())
        self.wid_initialStateVectorTitle.setSizePolicy(sizePolicy)
        self.wid_initialStateVectorTitle.setMinimumSize(QtCore.QSize(0, 70))
        self.wid_initialStateVectorTitle.setStyleSheet("background-color: white")
        self.wid_initialStateVectorTitle.setObjectName("wid_initialStateVectorTitle")
        self.la_initialStateVector = QtWidgets.QLabel(self.wid_initialStateVectorTitle)
        self.la_initialStateVector.setGeometry(QtCore.QRect(20, 10, 571, 60))
        self.la_initialStateVector.setMinimumSize(QtCore.QSize(0, 60))
        self.la_initialStateVector.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.la_initialStateVector.setFont(font)
        self.la_initialStateVector.setScaledContents(False)
        self.la_initialStateVector.setObjectName("la_initialStateVector")
        self.wid_initialStateVector_2 = QtWidgets.QWidget(self.wid_initialStateVectorTitle)
        self.wid_initialStateVector_2.setGeometry(QtCore.QRect(0, 77, 555, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_initialStateVector_2.sizePolicy().hasHeightForWidth())
        self.wid_initialStateVector_2.setSizePolicy(sizePolicy)
        self.wid_initialStateVector_2.setMinimumSize(QtCore.QSize(0, 70))
        self.wid_initialStateVector_2.setStyleSheet("background-color: white")
        self.wid_initialStateVector_2.setObjectName("wid_initialStateVector_2")
        self.verticalLayout_4.addWidget(self.wid_initialStateVectorTitle)
        self.wid_initialStateVector = QtWidgets.QWidget(self.wid_scrollArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_initialStateVector.sizePolicy().hasHeightForWidth())
        self.wid_initialStateVector.setSizePolicy(sizePolicy)
        self.wid_initialStateVector.setMinimumSize(QtCore.QSize(0, 70))
        self.wid_initialStateVector.setStyleSheet("background-color: white")
        self.wid_initialStateVector.setObjectName("wid_initialStateVector")
        self.verticalLayout_4.addWidget(self.wid_initialStateVector)
        self.wid_factorDistriution = QtWidgets.QWidget(self.wid_scrollArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_factorDistriution.sizePolicy().hasHeightForWidth())
        self.wid_factorDistriution.setSizePolicy(sizePolicy)
        self.wid_factorDistriution.setMinimumSize(QtCore.QSize(0, 70))
        self.wid_factorDistriution.setStyleSheet("background-color: white")
        self.wid_factorDistriution.setObjectName("wid_factorDistriution")
        self.la_factorDistribution = QtWidgets.QLabel(self.wid_factorDistriution)
        self.la_factorDistribution.setGeometry(QtCore.QRect(20, 10, 571, 60))
        self.la_factorDistribution.setMinimumSize(QtCore.QSize(0, 60))
        self.la_factorDistribution.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.la_factorDistribution.setFont(font)
        self.la_factorDistribution.setScaledContents(False)
        self.la_factorDistribution.setObjectName("la_factorDistribution")
        self.verticalLayout_4.addWidget(self.wid_factorDistriution)
        self.wid_factorDistribution = QtWidgets.QWidget(self.wid_scrollArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_factorDistribution.sizePolicy().hasHeightForWidth())
        self.wid_factorDistribution.setSizePolicy(sizePolicy)
        self.wid_factorDistribution.setMinimumSize(QtCore.QSize(0, 70))
        self.wid_factorDistribution.setStyleSheet("background-color: white")
        self.wid_factorDistribution.setObjectName("wid_factorDistribution")
        self.verticalLayout_4.addWidget(self.wid_factorDistribution)
        self.scrollArea.setWidget(self.wid_scrollArea)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.layoutInput = QtWidgets.QVBoxLayout()
        self.layoutInput.setObjectName("layoutInput")
        self.verticalLayout_3.addLayout(self.layoutInput)
        self.tabWidget_inputVisualisation.addTab(self.mc1, "")
        self.layoutInput_2.addWidget(self.tabWidget_inputVisualisation)
        self.widget = QtWidgets.QWidget(self.frameInput)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(11)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_addMC = QtWidgets.QPushButton(self.widget)
        self.pushButton_addMC.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_addMC.setFont(font)
        self.pushButton_addMC.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_addMC.setObjectName("pushButton_addMC")
        self.horizontalLayout_2.addWidget(self.pushButton_addMC)
        self.layoutInput_2.addWidget(self.widget, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frameInput)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(ProjectTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(-1, 13, -1, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_MC_2 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_MC_2.sizePolicy().hasHeightForWidth())
        self.label_MC_2.setSizePolicy(sizePolicy)
        self.label_MC_2.setMinimumSize(QtCore.QSize(144, 0))
        self.label_MC_2.setSizeIncrement(QtCore.QSize(34, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_MC_2.setFont(font)
        self.label_MC_2.setObjectName("label_MC_2")
        self.verticalLayout_2.addWidget(self.label_MC_2)
        self.tabWidget_resultVisualisation = QtWidgets.QTabWidget(self.frame_3)
        self.tabWidget_resultVisualisation.setObjectName("tabWidget_resultVisualisation")
        self.verticalLayout_2.addWidget(self.tabWidget_resultVisualisation)
        self.w_calculation_characteristivs = QtWidgets.QWidget(self.frame_3)
        self.w_calculation_characteristivs.setMinimumSize(QtCore.QSize(0, 30))
        self.w_calculation_characteristivs.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.w_calculation_characteristivs.setObjectName("w_calculation_characteristivs")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.w_calculation_characteristivs)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_chMethod = QtWidgets.QPushButton(self.w_calculation_characteristivs)
        self.pushButton_chMethod.setEnabled(False)
        self.pushButton_chMethod.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_chMethod.setFont(font)
        self.pushButton_chMethod.setObjectName("pushButton_chMethod")
        self.horizontalLayout_3.addWidget(self.pushButton_chMethod)
        self.pushButton_cancelAnalysis = QtWidgets.QPushButton(self.w_calculation_characteristivs)
        self.pushButton_cancelAnalysis.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cancelAnalysis.setFont(font)
        self.pushButton_cancelAnalysis.setObjectName("pushButton_cancelAnalysis")
        self.horizontalLayout_3.addWidget(self.pushButton_cancelAnalysis)
        self.le_currentPrecision = QtWidgets.QLineEdit(self.w_calculation_characteristivs)
        self.le_currentPrecision.setText("")
        self.le_currentPrecision.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_currentPrecision.setObjectName("le_currentPrecision")
        self.horizontalLayout_3.addWidget(self.le_currentPrecision)
        self.la_currenPrecision = QtWidgets.QLabel(self.w_calculation_characteristivs)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_currenPrecision.setFont(font)
        self.la_currenPrecision.setObjectName("la_currenPrecision")
        self.horizontalLayout_3.addWidget(self.la_currenPrecision)
        self.le_currentStep = QtWidgets.QLineEdit(self.w_calculation_characteristivs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_currentStep.sizePolicy().hasHeightForWidth())
        self.le_currentStep.setSizePolicy(sizePolicy)
        self.le_currentStep.setMaximumSize(QtCore.QSize(100, 16777215))
        self.le_currentStep.setText("")
        self.le_currentStep.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_currentStep.setObjectName("le_currentStep")
        self.horizontalLayout_3.addWidget(self.le_currentStep)
        self.la_currentStep = QtWidgets.QLabel(self.w_calculation_characteristivs)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_currentStep.setFont(font)
        self.la_currentStep.setObjectName("la_currentStep")
        self.horizontalLayout_3.addWidget(self.la_currentStep)
        self.verticalLayout_2.addWidget(self.w_calculation_characteristivs)
        self.horizontalLayout.addWidget(self.frame_3)

        self.retranslateUi(ProjectTab)
        self.tabWidget_inputVisualisation.setCurrentIndex(0)
        self.tabWidget_resultVisualisation.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(ProjectTab)

    def retranslateUi(self, ProjectTab):
        _translate = QtCore.QCoreApplication.translate
        ProjectTab.setWindowTitle(_translate("ProjectTab", "Form"))
        self.label_MC.setText(_translate("ProjectTab", "Markov Chain"))
        self.la_initialStateVector.setText(_translate("ProjectTab", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:400;\">Initial state distribution:</span></p></body></html>"))
        self.la_factorDistribution.setText(_translate("ProjectTab", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:400;\">Factor distribution:</span></p></body></html>"))
        self.tabWidget_inputVisualisation.setTabText(self.tabWidget_inputVisualisation.indexOf(self.mc1), _translate("ProjectTab", "MC 1"))
        self.pushButton_addMC.setText(_translate("ProjectTab", "Add Markov Chain"))
        self.label_MC_2.setText(_translate("ProjectTab", "Results"))
        self.pushButton_chMethod.setText(_translate("ProjectTab", "Analyse Markov Chain"))
        self.pushButton_cancelAnalysis.setText(_translate("ProjectTab", "Cancel Analysis"))
        self.la_currenPrecision.setText(_translate("ProjectTab", "Current precision:"))
        self.la_currentStep.setText(_translate("ProjectTab", "Current step:"))

