
#  Copyright (C) 2018 University of Tuebingen
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, version 3.
#
#  This program is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program. If not, see <http://www.gnu.org/licenses/>.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SystemSpezificationDialog(object):

    def setupUi(self, SystemSpezificationDialog):
        SystemSpezificationDialog.setObjectName("SystemSpezificationDialog")
        SystemSpezificationDialog.setWindowModality(QtCore.Qt.WindowModal)
        SystemSpezificationDialog.resize(1507, 989)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SystemSpezificationDialog.sizePolicy().hasHeightForWidth())
        SystemSpezificationDialog.setSizePolicy(sizePolicy)
        self.vl_system = QtWidgets.QVBoxLayout(SystemSpezificationDialog)
        self.vl_system.setObjectName("vl_system")
        self.tw_system = QtWidgets.QTabWidget(SystemSpezificationDialog)
        self.tw_system.setObjectName("tw_system")
        self.qw_systemSpecificationDialog = QtWidgets.QWidget()
        self.qw_systemSpecificationDialog.setObjectName("qw_systemSpecificationDialog")
        self.vl_systemSpecificationDialog = QtWidgets.QVBoxLayout(self.qw_systemSpecificationDialog)
        self.vl_systemSpecificationDialog.setContentsMargins(0, 0, 0, 0)
        self.vl_systemSpecificationDialog.setObjectName("vl_systemSpecificationDialog")
        self.qw_splittedLayout = QtWidgets.QWidget(self.qw_systemSpecificationDialog)
        self.qw_splittedLayout.setObjectName("qw_splittedLayout")
        self.hl_SplittedLayout = QtWidgets.QHBoxLayout(self.qw_splittedLayout)
        self.hl_SplittedLayout.setContentsMargins(0, 0, 0, 0)
        self.hl_SplittedLayout.setObjectName("hl_SplittedLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.qw_splittedLayout)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("background-color: white")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.wid_scrollArea = QtWidgets.QWidget()
        self.wid_scrollArea.setGeometry(QtCore.QRect(0, 0, 683, 1422))
        self.wid_scrollArea.setObjectName("wid_scrollArea")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.wid_scrollArea)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wid_qmax_2 = QtWidgets.QWidget(self.wid_scrollArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_qmax_2.sizePolicy().hasHeightForWidth())
        self.wid_qmax_2.setSizePolicy(sizePolicy)
        self.wid_qmax_2.setMinimumSize(QtCore.QSize(0, 1400))
        self.wid_qmax_2.setStyleSheet("background-color: white")
        self.wid_qmax_2.setObjectName("wid_qmax_2")
        self.wid_separatedFactors = QtWidgets.QWidget(self.wid_qmax_2)
        self.wid_separatedFactors.setGeometry(QtCore.QRect(0, 1240, 621, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_separatedFactors.sizePolicy().hasHeightForWidth())
        self.wid_separatedFactors.setSizePolicy(sizePolicy)
        self.wid_separatedFactors.setMinimumSize(QtCore.QSize(0, 120))
        self.wid_separatedFactors.setStyleSheet("background-color: white")
        self.wid_separatedFactors.setObjectName("wid_separatedFactors")
        self.cb_separateFactorDistributions = QtWidgets.QCheckBox(self.wid_separatedFactors)
        self.cb_separateFactorDistributions.setGeometry(QtCore.QRect(40, 20, 651, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cb_separateFactorDistributions.setFont(font)
        self.cb_separateFactorDistributions.setChecked(True)
        self.cb_separateFactorDistributions.setObjectName("cb_separateFactorDistributions")
        self.wid_qmax = QtWidgets.QWidget(self.wid_qmax_2)
        self.wid_qmax.setGeometry(QtCore.QRect(0, 876, 651, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_qmax.sizePolicy().hasHeightForWidth())
        self.wid_qmax.setSizePolicy(sizePolicy)
        self.wid_qmax.setMinimumSize(QtCore.QSize(0, 100))
        self.wid_qmax.setStyleSheet("background-color: white")
        self.wid_qmax.setObjectName("wid_qmax")
        self.le_qmax = QtWidgets.QLineEdit(self.wid_qmax)
        self.le_qmax.setGeometry(QtCore.QRect(480, 30, 151, 31))
        self.le_qmax.setObjectName("le_qmax")
        self.la_qmax = QtWidgets.QLabel(self.wid_qmax)
        self.la_qmax.setGeometry(QtCore.QRect(50, 20, 161, 60))
        self.la_qmax.setMinimumSize(QtCore.QSize(0, 60))
        self.la_qmax.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.la_qmax.setFont(font)
        self.la_qmax.setScaledContents(False)
        self.la_qmax.setObjectName("la_qmax")
        self.wid_title = QtWidgets.QWidget(self.wid_qmax_2)
        self.wid_title.setGeometry(QtCore.QRect(0, -12, 621, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_title.sizePolicy().hasHeightForWidth())
        self.wid_title.setSizePolicy(sizePolicy)
        self.wid_title.setMinimumSize(QtCore.QSize(0, 100))
        self.wid_title.setStyleSheet("background-color: white")
        self.wid_title.setObjectName("wid_title")
        self.la_sytemType = QtWidgets.QLabel(self.wid_title)
        self.la_sytemType.setGeometry(QtCore.QRect(30, 30, 571, 60))
        self.la_sytemType.setMinimumSize(QtCore.QSize(0, 60))
        self.la_sytemType.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.la_sytemType.setFont(font)
        self.la_sytemType.setScaledContents(False)
        self.la_sytemType.setObjectName("la_sytemType")
        self.wid_arrivalTimeDistribution = QtWidgets.QWidget(self.wid_qmax_2)
        self.wid_arrivalTimeDistribution.setGeometry(QtCore.QRect(0, 95, 651, 320))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_arrivalTimeDistribution.sizePolicy().hasHeightForWidth())
        self.wid_arrivalTimeDistribution.setSizePolicy(sizePolicy)
        self.wid_arrivalTimeDistribution.setMinimumSize(QtCore.QSize(0, 320))
        self.wid_arrivalTimeDistribution.setStyleSheet("background-color: white")
        self.wid_arrivalTimeDistribution.setObjectName("wid_arrivalTimeDistribution")
        self.la_arrivalTimeDistribution = QtWidgets.QLabel(self.wid_arrivalTimeDistribution)
        self.la_arrivalTimeDistribution.setGeometry(QtCore.QRect(40, 20, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.la_arrivalTimeDistribution.setFont(font)
        self.la_arrivalTimeDistribution.setObjectName("la_arrivalTimeDistribution")
        self.le_inputValuesArrivalTime = QtWidgets.QLineEdit(self.wid_arrivalTimeDistribution)
        self.le_inputValuesArrivalTime.setGeometry(QtCore.QRect(390, 120, 241, 31))
        self.le_inputValuesArrivalTime.setObjectName("le_inputValuesArrivalTime")
        self.la_probabilitiesArrivalTime = QtWidgets.QLabel(self.wid_arrivalTimeDistribution)
        self.la_probabilitiesArrivalTime.setGeometry(QtCore.QRect(100, 160, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_probabilitiesArrivalTime.setFont(font)
        self.la_probabilitiesArrivalTime.setObjectName("la_probabilitiesArrivalTime")
        self.cob_arrivalTimeDistribution = QtWidgets.QComboBox(self.wid_arrivalTimeDistribution)
        self.cob_arrivalTimeDistribution.setGeometry(QtCore.QRect(390, 30, 241, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.cob_arrivalTimeDistribution.setPalette(palette)
        self.cob_arrivalTimeDistribution.setStyleSheet("background-color:rgb(234, 234, 234)")
        self.cob_arrivalTimeDistribution.setObjectName("cob_arrivalTimeDistribution")
        self.cob_arrivalTimeDistribution.addItem("")
        self.cob_arrivalTimeDistribution.addItem("")
        self.cob_arrivalTimeDistribution.addItem("")
        self.cob_arrivalTimeDistribution.addItem("")
        self.cob_arrivalTimeDistribution.addItem("")
        self.cob_arrivalTimeDistribution.addItem("")
        self.cob_arrivalTimeDistribution.addItem("")
        self.la_inputValuesArrivalTime = QtWidgets.QLabel(self.wid_arrivalTimeDistribution)
        self.la_inputValuesArrivalTime.setGeometry(QtCore.QRect(100, 110, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_inputValuesArrivalTime.setFont(font)
        self.la_inputValuesArrivalTime.setObjectName("la_inputValuesArrivalTime")
        self.le_probabiliesArrivalTime = QtWidgets.QLineEdit(self.wid_arrivalTimeDistribution)
        self.le_probabiliesArrivalTime.setGeometry(QtCore.QRect(390, 170, 241, 31))
        self.le_probabiliesArrivalTime.setObjectName("le_probabiliesArrivalTime")
        self.le_maximumArrivalTime = QtWidgets.QLineEdit(self.wid_arrivalTimeDistribution)
        self.le_maximumArrivalTime.setGeometry(QtCore.QRect(480, 80, 151, 31))
        self.le_maximumArrivalTime.setObjectName("le_maximumArrivalTime")
        self.rb_listInputArrivalTime = QtWidgets.QRadioButton(self.wid_arrivalTimeDistribution)
        self.rb_listInputArrivalTime.setGeometry(QtCore.QRect(60, 80, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_listInputArrivalTime.setFont(font)
        self.rb_listInputArrivalTime.setChecked(True)
        self.rb_listInputArrivalTime.setObjectName("rb_listInputArrivalTime")
        self.le_fileInputArrivalTime = QtWidgets.QLineEdit(self.wid_arrivalTimeDistribution)
        self.le_fileInputArrivalTime.setGeometry(QtCore.QRect(390, 220, 181, 31))
        self.le_fileInputArrivalTime.setObjectName("le_fileInputArrivalTime")
        self.rb_fileInputArrivalTime = QtWidgets.QRadioButton(self.wid_arrivalTimeDistribution)
        self.rb_fileInputArrivalTime.setGeometry(QtCore.QRect(60, 230, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_fileInputArrivalTime.setFont(font)
        self.rb_fileInputArrivalTime.setObjectName("rb_fileInputArrivalTime")
        self.le_rateArrivalTime = QtWidgets.QLineEdit(self.wid_arrivalTimeDistribution)
        self.le_rateArrivalTime.setGeometry(QtCore.QRect(480, 130, 151, 31))
        self.le_rateArrivalTime.setObjectName("le_rateArrivalTime")
        self.la_rateArrivalTime = QtWidgets.QLabel(self.wid_arrivalTimeDistribution)
        self.la_rateArrivalTime.setGeometry(QtCore.QRect(100, 120, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_rateArrivalTime.setFont(font)
        self.la_rateArrivalTime.setObjectName("la_rateArrivalTime")
        self.le_kArrivalTime = QtWidgets.QLineEdit(self.wid_arrivalTimeDistribution)
        self.le_kArrivalTime.setGeometry(QtCore.QRect(480, 180, 151, 31))
        self.le_kArrivalTime.setObjectName("le_kArrivalTime")
        self.la_kArrivalTime = QtWidgets.QLabel(self.wid_arrivalTimeDistribution)
        self.la_kArrivalTime.setGeometry(QtCore.QRect(100, 170, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_kArrivalTime.setFont(font)
        self.la_kArrivalTime.setObjectName("la_kArrivalTime")
        self.bu_filePath_ArrivalTime = QtWidgets.QPushButton(self.wid_arrivalTimeDistribution)
        self.bu_filePath_ArrivalTime.setGeometry(QtCore.QRect(571, 220, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bu_filePath_ArrivalTime.setFont(font)
        self.bu_filePath_ArrivalTime.setObjectName("bu_filePath_ArrivalTime")
        self.cb_maximumArrivalTime = QtWidgets.QCheckBox(self.wid_arrivalTimeDistribution)
        self.cb_maximumArrivalTime.setGeometry(QtCore.QRect(78, 60, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_maximumArrivalTime.setFont(font)
        self.cb_maximumArrivalTime.setObjectName("cb_maximumArrivalTime")
        self.la_betaArrivalTime = QtWidgets.QLabel(self.wid_arrivalTimeDistribution)
        self.la_betaArrivalTime.setGeometry(QtCore.QRect(100, 170, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_betaArrivalTime.setFont(font)
        self.la_betaArrivalTime.setObjectName("la_betaArrivalTime")
        self.le_betaArrivalTime = QtWidgets.QLineEdit(self.wid_arrivalTimeDistribution)
        self.le_betaArrivalTime.setGeometry(QtCore.QRect(480, 180, 151, 31))
        self.le_betaArrivalTime.setObjectName("le_betaArrivalTime")
        self.le_alphaArrivalTime = QtWidgets.QLineEdit(self.wid_arrivalTimeDistribution)
        self.le_alphaArrivalTime.setGeometry(QtCore.QRect(480, 130, 151, 31))
        self.le_alphaArrivalTime.setObjectName("le_alphaArrivalTime")
        self.la_alphaArrivalTime = QtWidgets.QLabel(self.wid_arrivalTimeDistribution)
        self.la_alphaArrivalTime.setGeometry(QtCore.QRect(100, 120, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_alphaArrivalTime.setFont(font)
        self.la_alphaArrivalTime.setObjectName("la_alphaArrivalTime")
        self.la_maxArrivalTime = QtWidgets.QLabel(self.wid_arrivalTimeDistribution)
        self.la_maxArrivalTime.setGeometry(QtCore.QRect(100, 120, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_maxArrivalTime.setFont(font)
        self.la_maxArrivalTime.setObjectName("la_maxArrivalTime")
        self.le_maxArrivalTime = QtWidgets.QLineEdit(self.wid_arrivalTimeDistribution)
        self.le_maxArrivalTime.setGeometry(QtCore.QRect(480, 130, 151, 31))
        self.le_maxArrivalTime.setObjectName("le_maxArrivalTime")
        self.la_minArrivalTime = QtWidgets.QLabel(self.wid_arrivalTimeDistribution)
        self.la_minArrivalTime.setGeometry(QtCore.QRect(100, 70, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_minArrivalTime.setFont(font)
        self.la_minArrivalTime.setObjectName("la_minArrivalTime")
        self.le_minArrivalTime = QtWidgets.QLineEdit(self.wid_arrivalTimeDistribution)
        self.le_minArrivalTime.setGeometry(QtCore.QRect(480, 80, 151, 31))
        self.le_minArrivalTime.setObjectName("le_minArrivalTime")
        self.la_liArrivalTime = QtWidgets.QLabel(self.wid_arrivalTimeDistribution)
        self.la_liArrivalTime.setGeometry(QtCore.QRect(100, 120, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_liArrivalTime.setFont(font)
        self.la_liArrivalTime.setObjectName("la_liArrivalTime")
        self.la_piArrivalTime = QtWidgets.QLabel(self.wid_arrivalTimeDistribution)
        self.la_piArrivalTime.setGeometry(QtCore.QRect(100, 170, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_piArrivalTime.setFont(font)
        self.la_piArrivalTime.setObjectName("la_piArrivalTime")
        self.le_liArrivalTime = QtWidgets.QLineEdit(self.wid_arrivalTimeDistribution)
        self.le_liArrivalTime.setGeometry(QtCore.QRect(480, 130, 151, 31))
        self.le_liArrivalTime.setObjectName("le_liArrivalTime")
        self.le_piArrivalTime = QtWidgets.QLineEdit(self.wid_arrivalTimeDistribution)
        self.le_piArrivalTime.setGeometry(QtCore.QRect(480, 180, 151, 31))
        self.le_piArrivalTime.setObjectName("le_piArrivalTime")
        self.wid_batchSizeDistribution = QtWidgets.QWidget(self.wid_qmax_2)
        self.wid_batchSizeDistribution.setGeometry(QtCore.QRect(0, 422, 651, 320))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_batchSizeDistribution.sizePolicy().hasHeightForWidth())
        self.wid_batchSizeDistribution.setSizePolicy(sizePolicy)
        self.wid_batchSizeDistribution.setMinimumSize(QtCore.QSize(0, 320))
        self.wid_batchSizeDistribution.setStyleSheet("background-color: white")
        self.wid_batchSizeDistribution.setObjectName("wid_batchSizeDistribution")
        self.le_inputValuesBatchSize = QtWidgets.QLineEdit(self.wid_batchSizeDistribution)
        self.le_inputValuesBatchSize.setGeometry(QtCore.QRect(390, 120, 241, 31))
        self.le_inputValuesBatchSize.setObjectName("le_inputValuesBatchSize")
        self.cob_batchSizeDistribution = QtWidgets.QComboBox(self.wid_batchSizeDistribution)
        self.cob_batchSizeDistribution.setGeometry(QtCore.QRect(390, 30, 241, 31))
        self.cob_batchSizeDistribution.setStyleSheet("background-color:rgb(234, 234, 234)")
        self.cob_batchSizeDistribution.setObjectName("cob_batchSizeDistribution")
        self.cob_batchSizeDistribution.addItem("")
        self.cob_batchSizeDistribution.addItem("")
        self.cob_batchSizeDistribution.addItem("")
        self.cob_batchSizeDistribution.addItem("")
        self.cob_batchSizeDistribution.addItem("")
        self.cob_batchSizeDistribution.addItem("")
        self.cob_batchSizeDistribution.addItem("")
        self.la_probabilitiesBatchSize = QtWidgets.QLabel(self.wid_batchSizeDistribution)
        self.la_probabilitiesBatchSize.setGeometry(QtCore.QRect(110, 160, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_probabilitiesBatchSize.setFont(font)
        self.la_probabilitiesBatchSize.setObjectName("la_probabilitiesBatchSize")
        self.la_inputValuesBatchSize = QtWidgets.QLabel(self.wid_batchSizeDistribution)
        self.la_inputValuesBatchSize.setGeometry(QtCore.QRect(110, 110, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_inputValuesBatchSize.setFont(font)
        self.la_inputValuesBatchSize.setObjectName("la_inputValuesBatchSize")
        self.la_batchSizeDistribution = QtWidgets.QLabel(self.wid_batchSizeDistribution)
        self.la_batchSizeDistribution.setGeometry(QtCore.QRect(50, 20, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.la_batchSizeDistribution.setFont(font)
        self.la_batchSizeDistribution.setObjectName("la_batchSizeDistribution")
        self.rb_fileInputBatchSize = QtWidgets.QRadioButton(self.wid_batchSizeDistribution)
        self.rb_fileInputBatchSize.setGeometry(QtCore.QRect(70, 230, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_fileInputBatchSize.setFont(font)
        self.rb_fileInputBatchSize.setChecked(False)
        self.rb_fileInputBatchSize.setObjectName("rb_fileInputBatchSize")
        self.le_probabiliesBatchSize = QtWidgets.QLineEdit(self.wid_batchSizeDistribution)
        self.le_probabiliesBatchSize.setGeometry(QtCore.QRect(390, 170, 241, 31))
        self.le_probabiliesBatchSize.setObjectName("le_probabiliesBatchSize")
        self.le_fileInputBatchSize = QtWidgets.QLineEdit(self.wid_batchSizeDistribution)
        self.le_fileInputBatchSize.setGeometry(QtCore.QRect(390, 220, 181, 31))
        self.le_fileInputBatchSize.setObjectName("le_fileInputBatchSize")
        self.le_maximumBatchSize = QtWidgets.QLineEdit(self.wid_batchSizeDistribution)
        self.le_maximumBatchSize.setGeometry(QtCore.QRect(480, 80, 151, 31))
        self.le_maximumBatchSize.setObjectName("le_maximumBatchSize")
        self.rb_listInputBatchSize = QtWidgets.QRadioButton(self.wid_batchSizeDistribution)
        self.rb_listInputBatchSize.setGeometry(QtCore.QRect(70, 80, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rb_listInputBatchSize.setFont(font)
        self.rb_listInputBatchSize.setChecked(True)
        self.rb_listInputBatchSize.setObjectName("rb_listInputBatchSize")
        self.le_rateBatchSize = QtWidgets.QLineEdit(self.wid_batchSizeDistribution)
        self.le_rateBatchSize.setGeometry(QtCore.QRect(480, 130, 151, 31))
        self.le_rateBatchSize.setObjectName("le_rateBatchSize")
        self.la_rateBatchSize = QtWidgets.QLabel(self.wid_batchSizeDistribution)
        self.la_rateBatchSize.setGeometry(QtCore.QRect(110, 120, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_rateBatchSize.setFont(font)
        self.la_rateBatchSize.setObjectName("la_rateBatchSize")
        self.la_kBatchSize = QtWidgets.QLabel(self.wid_batchSizeDistribution)
        self.la_kBatchSize.setGeometry(QtCore.QRect(110, 170, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_kBatchSize.setFont(font)
        self.la_kBatchSize.setObjectName("la_kBatchSize")
        self.le_kBatchSize = QtWidgets.QLineEdit(self.wid_batchSizeDistribution)
        self.le_kBatchSize.setGeometry(QtCore.QRect(480, 180, 151, 31))
        self.le_kBatchSize.setObjectName("le_kBatchSize")
        self.bu_filePath_BatchSize = QtWidgets.QPushButton(self.wid_batchSizeDistribution)
        self.bu_filePath_BatchSize.setGeometry(QtCore.QRect(571, 220, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bu_filePath_BatchSize.setFont(font)
        self.bu_filePath_BatchSize.setObjectName("bu_filePath_BatchSize")
        self.cb_maximumBatchSize = QtWidgets.QCheckBox(self.wid_batchSizeDistribution)
        self.cb_maximumBatchSize.setGeometry(QtCore.QRect(90, 70, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_maximumBatchSize.setFont(font)
        self.cb_maximumBatchSize.setObjectName("cb_maximumBatchSize")
        self.la_alphaBatchSize = QtWidgets.QLabel(self.wid_batchSizeDistribution)
        self.la_alphaBatchSize.setGeometry(QtCore.QRect(110, 120, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_alphaBatchSize.setFont(font)
        self.la_alphaBatchSize.setObjectName("la_alphaBatchSize")
        self.la_betaBatchSize = QtWidgets.QLabel(self.wid_batchSizeDistribution)
        self.la_betaBatchSize.setGeometry(QtCore.QRect(110, 170, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_betaBatchSize.setFont(font)
        self.la_betaBatchSize.setObjectName("la_betaBatchSize")
        self.le_betaBatchSize = QtWidgets.QLineEdit(self.wid_batchSizeDistribution)
        self.le_betaBatchSize.setGeometry(QtCore.QRect(480, 180, 151, 31))
        self.le_betaBatchSize.setObjectName("le_betaBatchSize")
        self.le_alphaBatchSize = QtWidgets.QLineEdit(self.wid_batchSizeDistribution)
        self.le_alphaBatchSize.setGeometry(QtCore.QRect(480, 130, 151, 31))
        self.le_alphaBatchSize.setObjectName("le_alphaBatchSize")
        self.le_maxBatchSize = QtWidgets.QLineEdit(self.wid_batchSizeDistribution)
        self.le_maxBatchSize.setGeometry(QtCore.QRect(480, 130, 151, 31))
        self.le_maxBatchSize.setObjectName("le_maxBatchSize")
        self.la_minBatchSize = QtWidgets.QLabel(self.wid_batchSizeDistribution)
        self.la_minBatchSize.setGeometry(QtCore.QRect(110, 70, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_minBatchSize.setFont(font)
        self.la_minBatchSize.setObjectName("la_minBatchSize")
        self.le_minBatchSize = QtWidgets.QLineEdit(self.wid_batchSizeDistribution)
        self.le_minBatchSize.setGeometry(QtCore.QRect(480, 80, 151, 31))
        self.le_minBatchSize.setObjectName("le_minBatchSize")
        self.la_maxBatchSize = QtWidgets.QLabel(self.wid_batchSizeDistribution)
        self.la_maxBatchSize.setGeometry(QtCore.QRect(110, 120, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_maxBatchSize.setFont(font)
        self.la_maxBatchSize.setObjectName("la_maxBatchSize")
        self.le_piBatchSize = QtWidgets.QLineEdit(self.wid_batchSizeDistribution)
        self.le_piBatchSize.setGeometry(QtCore.QRect(480, 180, 151, 31))
        self.le_piBatchSize.setObjectName("le_piBatchSize")
        self.la_liBatchSize = QtWidgets.QLabel(self.wid_batchSizeDistribution)
        self.la_liBatchSize.setGeometry(QtCore.QRect(100, 120, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_liBatchSize.setFont(font)
        self.la_liBatchSize.setObjectName("la_liBatchSize")
        self.le_liBatchSize = QtWidgets.QLineEdit(self.wid_batchSizeDistribution)
        self.le_liBatchSize.setGeometry(QtCore.QRect(480, 130, 151, 31))
        self.le_liBatchSize.setObjectName("le_liBatchSize")
        self.la_piBatchSize = QtWidgets.QLabel(self.wid_batchSizeDistribution)
        self.la_piBatchSize.setGeometry(QtCore.QRect(100, 170, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.la_piBatchSize.setFont(font)
        self.la_piBatchSize.setObjectName("la_piBatchSize")
        self.wid_transitionFunction = QtWidgets.QWidget(self.wid_qmax_2)
        self.wid_transitionFunction.setGeometry(QtCore.QRect(0, 980, 651, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_transitionFunction.sizePolicy().hasHeightForWidth())
        self.wid_transitionFunction.setSizePolicy(sizePolicy)
        self.wid_transitionFunction.setMinimumSize(QtCore.QSize(0, 200))
        self.wid_transitionFunction.setStyleSheet("background-color: white")
        self.wid_transitionFunction.setObjectName("wid_transitionFunction")
        self.tw_transitionFunctions = QtWidgets.QTabWidget(self.wid_transitionFunction)
        self.tw_transitionFunctions.setGeometry(QtCore.QRect(50, 80, 581, 178))
        self.tw_transitionFunctions.setTabsClosable(False)
        self.tw_transitionFunctions.setObjectName("tw_transitionFunctions")
        self.la_transitionFunction = QtWidgets.QLabel(self.wid_transitionFunction)
        self.la_transitionFunction.setGeometry(QtCore.QRect(50, 20, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.la_transitionFunction.setFont(font)
        self.la_transitionFunction.setObjectName("la_transitionFunction")
        self.wid_serviceTime = QtWidgets.QWidget(self.wid_qmax_2)
        self.wid_serviceTime.setGeometry(QtCore.QRect(0, 749, 651, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_serviceTime.sizePolicy().hasHeightForWidth())
        self.wid_serviceTime.setSizePolicy(sizePolicy)
        self.wid_serviceTime.setMinimumSize(QtCore.QSize(0, 120))
        self.wid_serviceTime.setStyleSheet("background-color: white")
        self.wid_serviceTime.setObjectName("wid_serviceTime")
        self.la_batchSize = QtWidgets.QLabel(self.wid_serviceTime)
        self.la_batchSize.setGeometry(QtCore.QRect(50, 20, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.la_batchSize.setFont(font)
        self.la_batchSize.setObjectName("la_batchSize")
        self.le_batchSize = QtWidgets.QLineEdit(self.wid_serviceTime)
        self.le_batchSize.setGeometry(QtCore.QRect(480, 30, 151, 31))
        self.le_batchSize.setObjectName("le_batchSize")
        self.cb_serviceTimeAdjustment = QtWidgets.QCheckBox(self.wid_serviceTime)
        self.cb_serviceTimeAdjustment.setGeometry(QtCore.QRect(80, 70, 461, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_serviceTimeAdjustment.setFont(font)
        self.cb_serviceTimeAdjustment.setStyleSheet("")
        self.cb_serviceTimeAdjustment.setObjectName("cb_serviceTimeAdjustment")
        self.verticalLayout.addWidget(self.wid_qmax_2)
        self.scrollArea.setWidget(self.wid_scrollArea)
        self.hl_SplittedLayout.addWidget(self.scrollArea)
        self.frame_systemVisualisation = QtWidgets.QFrame(self.qw_splittedLayout)
        self.frame_systemVisualisation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_systemVisualisation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_systemVisualisation.setObjectName("frame_systemVisualisation")
        self.vl_SystemVisualisation = QtWidgets.QVBoxLayout(self.frame_systemVisualisation)
        self.vl_SystemVisualisation.setObjectName("vl_SystemVisualisation")
        self.la_arrivalTimeDistributionFunction = QtWidgets.QLabel(self.frame_systemVisualisation)
        self.la_arrivalTimeDistributionFunction.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.la_arrivalTimeDistributionFunction.setFont(font)
        self.la_arrivalTimeDistributionFunction.setObjectName("la_arrivalTimeDistributionFunction")
        self.vl_SystemVisualisation.addWidget(self.la_arrivalTimeDistributionFunction)
        self.wid_arrivalTimeDistributionFunction = QtWidgets.QWidget(self.frame_systemVisualisation)
        self.wid_arrivalTimeDistributionFunction.setObjectName("wid_arrivalTimeDistributionFunction")
        self.vl_arrivalTimeDistributionVisualisation = QtWidgets.QVBoxLayout(self.wid_arrivalTimeDistributionFunction)
        self.vl_arrivalTimeDistributionVisualisation.setContentsMargins(0, 0, 0, 0)
        self.vl_arrivalTimeDistributionVisualisation.setObjectName("vl_arrivalTimeDistributionVisualisation")
        self.vl_SystemVisualisation.addWidget(self.wid_arrivalTimeDistributionFunction)
        self.w_toolbarArrivalOuter = QtWidgets.QWidget(self.frame_systemVisualisation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_toolbarArrivalOuter.sizePolicy().hasHeightForWidth())
        self.w_toolbarArrivalOuter.setSizePolicy(sizePolicy)
        self.w_toolbarArrivalOuter.setMinimumSize(QtCore.QSize(700, 60))
        self.w_toolbarArrivalOuter.setMaximumSize(QtCore.QSize(700, 60))
        self.w_toolbarArrivalOuter.setObjectName("w_toolbarArrivalOuter")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.w_toolbarArrivalOuter)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-3, 0, 701, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.hl_toolbarArrivalOuter = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.hl_toolbarArrivalOuter.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.hl_toolbarArrivalOuter.setContentsMargins(0, 0, 0, 0)
        self.hl_toolbarArrivalOuter.setObjectName("hl_toolbarArrivalOuter")
        self.w_toolbarArrival = QtWidgets.QWidget(self.w_toolbarArrivalOuter)
        self.w_toolbarArrival.setGeometry(QtCore.QRect(0, 0, 700, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_toolbarArrival.sizePolicy().hasHeightForWidth())
        self.w_toolbarArrival.setSizePolicy(sizePolicy)
        self.w_toolbarArrival.setMinimumSize(QtCore.QSize(700, 60))
        self.w_toolbarArrival.setMaximumSize(QtCore.QSize(700, 60))
        self.w_toolbarArrival.setObjectName("w_toolbarArrival")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.w_toolbarArrival)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 331, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.hl_toolbarArrival = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.hl_toolbarArrival.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.hl_toolbarArrival.setContentsMargins(0, 0, 0, 0)
        self.hl_toolbarArrival.setObjectName("hl_toolbarArrival")
        self.vl_SystemVisualisation.addWidget(self.w_toolbarArrivalOuter)
        self.la_batchSizeDistributionFunction = QtWidgets.QLabel(self.frame_systemVisualisation)
        self.la_batchSizeDistributionFunction.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.la_batchSizeDistributionFunction.setFont(font)
        self.la_batchSizeDistributionFunction.setObjectName("la_batchSizeDistributionFunction")
        self.vl_SystemVisualisation.addWidget(self.la_batchSizeDistributionFunction)
        self.wid_batchSizeDistributionFunction = QtWidgets.QWidget(self.frame_systemVisualisation)
        self.wid_batchSizeDistributionFunction.setObjectName("wid_batchSizeDistributionFunction")
        self.vl_batchSizeDistributionVisualisation = QtWidgets.QVBoxLayout(self.wid_batchSizeDistributionFunction)
        self.vl_batchSizeDistributionVisualisation.setContentsMargins(0, 0, 0, 0)
        self.vl_batchSizeDistributionVisualisation.setObjectName("vl_batchSizeDistributionVisualisation")
        self.vl_SystemVisualisation.addWidget(self.wid_batchSizeDistributionFunction)
        self.w_toolbarBatchOuter = QtWidgets.QWidget(self.frame_systemVisualisation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_toolbarBatchOuter.sizePolicy().hasHeightForWidth())
        self.w_toolbarBatchOuter.setSizePolicy(sizePolicy)
        self.w_toolbarBatchOuter.setMinimumSize(QtCore.QSize(700, 60))
        self.w_toolbarBatchOuter.setMaximumSize(QtCore.QSize(700, 60))
        self.w_toolbarBatchOuter.setObjectName("w_toolbarBatchOuter")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.w_toolbarBatchOuter)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(-3, 0, 701, 51))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.hl_toolbarBatchOuter = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.hl_toolbarBatchOuter.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.hl_toolbarBatchOuter.setContentsMargins(0, 0, 0, 0)
        self.hl_toolbarBatchOuter.setObjectName("hl_toolbarBatchOuter")
        self.w_toolbarBatch = QtWidgets.QWidget(self.w_toolbarBatchOuter)
        self.w_toolbarBatch.setGeometry(QtCore.QRect(0, 0, 700, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_toolbarBatch.sizePolicy().hasHeightForWidth())
        self.w_toolbarBatch.setSizePolicy(sizePolicy)
        self.w_toolbarBatch.setMinimumSize(QtCore.QSize(700, 60))
        self.w_toolbarBatch.setMaximumSize(QtCore.QSize(700, 60))
        self.w_toolbarBatch.setObjectName("w_toolbarBatch")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.w_toolbarBatch)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(0, 0, 331, 51))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.hl_toolbarBatch = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.hl_toolbarBatch.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.hl_toolbarBatch.setContentsMargins(0, 0, 0, 0)
        self.hl_toolbarBatch.setObjectName("hl_toolbarBatch")
        self.vl_SystemVisualisation.addWidget(self.w_toolbarBatchOuter)
        self.hl_SplittedLayout.addWidget(self.frame_systemVisualisation)
        self.vl_systemSpecificationDialog.addWidget(self.qw_splittedLayout)
        self.tw_system.addTab(self.qw_systemSpecificationDialog, "")
        self.vl_system.addWidget(self.tw_system)
        self.bb_processingOperation = QtWidgets.QDialogButtonBox(SystemSpezificationDialog)
        self.bb_processingOperation.setOrientation(QtCore.Qt.Horizontal)
        self.bb_processingOperation.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.bb_processingOperation.setCenterButtons(False)
        self.bb_processingOperation.setObjectName("bb_processingOperation")
        self.vl_system.addWidget(self.bb_processingOperation)

        self.retranslateUi(SystemSpezificationDialog)
        self.tw_transitionFunctions.setCurrentIndex(-1)
        self.bb_processingOperation.accepted.connect(SystemSpezificationDialog.accept)
        self.bb_processingOperation.rejected.connect(SystemSpezificationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SystemSpezificationDialog)

    def retranslateUi(self, SystemSpezificationDialog):
        _translate = QtCore.QCoreApplication.translate
        SystemSpezificationDialog.setWindowTitle(_translate("SystemSpezificationDialog", "System Specification Dialog"))
        self.cb_separateFactorDistributions.setText(_translate("SystemSpezificationDialog", "Separated Factor Distributions"))
        self.le_qmax.setText(_translate("SystemSpezificationDialog", "30"))
        self.la_qmax.setText(_translate("SystemSpezificationDialog", "<html><head/><body><p>Q<span style=\" vertical-align:sub;\">max</span></p></body></html>"))
        self.la_sytemType.setText(_translate("SystemSpezificationDialog", "<html><head/><body><p>GI<span style=\" vertical-align:super;\">[GI]</span>/D/1 - Q<span style=\" vertical-align:sub;\">max</span> - System</p></body></html>"))
        self.la_arrivalTimeDistribution.setText(_translate("SystemSpezificationDialog", "Arrival-Time Distribution:"))
        self.le_inputValuesArrivalTime.setText(_translate("SystemSpezificationDialog", "2, 5, 8"))
        self.la_probabilitiesArrivalTime.setText(_translate("SystemSpezificationDialog", "Probabilites:"))
        self.cob_arrivalTimeDistribution.setItemText(0, _translate("SystemSpezificationDialog", "-"))
        self.cob_arrivalTimeDistribution.setItemText(1, _translate("SystemSpezificationDialog", "General independent distribution"))
        self.cob_arrivalTimeDistribution.setItemText(2, _translate("SystemSpezificationDialog", "Exponential distribution"))
        self.cob_arrivalTimeDistribution.setItemText(3, _translate("SystemSpezificationDialog", "K-Erlang distribution"))
        self.cob_arrivalTimeDistribution.setItemText(4, _translate("SystemSpezificationDialog", "Hyperexponential distribution"))
        self.cob_arrivalTimeDistribution.setItemText(5, _translate("SystemSpezificationDialog", "Gamma distribution"))
        self.cob_arrivalTimeDistribution.setItemText(6, _translate("SystemSpezificationDialog", "Uniform distribution"))
        self.la_inputValuesArrivalTime.setText(_translate("SystemSpezificationDialog", "Input values:"))
        self.le_probabiliesArrivalTime.setText(_translate("SystemSpezificationDialog", "0.347222222, 0.305555556 ,0.347222222 "))
        self.le_maximumArrivalTime.setText(_translate("SystemSpezificationDialog", "None"))
        self.rb_listInputArrivalTime.setText(_translate("SystemSpezificationDialog", "List input"))
        self.le_fileInputArrivalTime.setText(_translate("SystemSpezificationDialog", "None"))
        self.rb_fileInputArrivalTime.setText(_translate("SystemSpezificationDialog", "File input:"))
        self.le_rateArrivalTime.setText(_translate("SystemSpezificationDialog", "1"))
        self.la_rateArrivalTime.setText(_translate("SystemSpezificationDialog", "Rate:"))
        self.le_kArrivalTime.setText(_translate("SystemSpezificationDialog", "5"))
        self.la_kArrivalTime.setText(_translate("SystemSpezificationDialog", "K:"))
        self.bu_filePath_ArrivalTime.setText(_translate("SystemSpezificationDialog", "URL"))
        self.cb_maximumArrivalTime.setText(_translate("SystemSpezificationDialog", "Maximum arrival time:"))
        self.la_betaArrivalTime.setText(_translate("SystemSpezificationDialog", "Beta:"))
        self.le_betaArrivalTime.setText(_translate("SystemSpezificationDialog", "5"))
        self.le_alphaArrivalTime.setText(_translate("SystemSpezificationDialog", "1"))
        self.la_alphaArrivalTime.setText(_translate("SystemSpezificationDialog", "Alpha:"))
        self.la_maxArrivalTime.setText(_translate("SystemSpezificationDialog", "Maximum:"))
        self.le_maxArrivalTime.setText(_translate("SystemSpezificationDialog", "5"))
        self.la_minArrivalTime.setText(_translate("SystemSpezificationDialog", "Minimum:"))
        self.le_minArrivalTime.setText(_translate("SystemSpezificationDialog", "0"))
        self.la_liArrivalTime.setText(_translate("SystemSpezificationDialog", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; font-size:14px; color:#222222; background-color:#ffffff;\">λ</span><span style=\" vertical-align:sub;\">i </span>:</p></body></html>"))
        self.la_piArrivalTime.setText(_translate("SystemSpezificationDialog", "<html><head/><body><p>p<span style=\" vertical-align:sub;\">i</span> :</p></body></html>"))
        self.le_liArrivalTime.setText(_translate("SystemSpezificationDialog", "1, 20"))
        self.le_piArrivalTime.setText(_translate("SystemSpezificationDialog", "0.1, 0.9"))
        self.le_inputValuesBatchSize.setText(_translate("SystemSpezificationDialog", "1, 2, 8"))
        self.cob_batchSizeDistribution.setItemText(0, _translate("SystemSpezificationDialog", "-"))
        self.cob_batchSizeDistribution.setItemText(1, _translate("SystemSpezificationDialog", "General independent distribution"))
        self.cob_batchSizeDistribution.setItemText(2, _translate("SystemSpezificationDialog", "Exponential distribution"))
        self.cob_batchSizeDistribution.setItemText(3, _translate("SystemSpezificationDialog", "K-Erlang distribution"))
        self.cob_batchSizeDistribution.setItemText(4, _translate("SystemSpezificationDialog", "Hyperexponential distribution"))
        self.cob_batchSizeDistribution.setItemText(5, _translate("SystemSpezificationDialog", "Gamma distribution"))
        self.cob_batchSizeDistribution.setItemText(6, _translate("SystemSpezificationDialog", "Uniform distribution"))
        self.la_probabilitiesBatchSize.setText(_translate("SystemSpezificationDialog", "Probabilites:"))
        self.la_inputValuesBatchSize.setText(_translate("SystemSpezificationDialog", "Input values:"))
        self.la_batchSizeDistribution.setText(_translate("SystemSpezificationDialog", "Batch-Size Distribution:"))
        self.rb_fileInputBatchSize.setText(_translate("SystemSpezificationDialog", "File input:"))
        self.le_probabiliesBatchSize.setText(_translate("SystemSpezificationDialog", "0.5, 0.333333333334, 0.166666666667 "))
        self.le_fileInputBatchSize.setText(_translate("SystemSpezificationDialog", "None"))
        self.le_maximumBatchSize.setText(_translate("SystemSpezificationDialog", "None"))
        self.rb_listInputBatchSize.setText(_translate("SystemSpezificationDialog", "List input"))
        self.le_rateBatchSize.setText(_translate("SystemSpezificationDialog", "1"))
        self.la_rateBatchSize.setText(_translate("SystemSpezificationDialog", "Rate:"))
        self.la_kBatchSize.setText(_translate("SystemSpezificationDialog", "K:"))
        self.le_kBatchSize.setText(_translate("SystemSpezificationDialog", "5"))
        self.bu_filePath_BatchSize.setText(_translate("SystemSpezificationDialog", "URL"))
        self.cb_maximumBatchSize.setText(_translate("SystemSpezificationDialog", "Maximum arrival time:"))
        self.la_alphaBatchSize.setText(_translate("SystemSpezificationDialog", "Alpha:"))
        self.la_betaBatchSize.setText(_translate("SystemSpezificationDialog", "Beta:"))
        self.le_betaBatchSize.setText(_translate("SystemSpezificationDialog", "5"))
        self.le_alphaBatchSize.setText(_translate("SystemSpezificationDialog", "1"))
        self.le_maxBatchSize.setText(_translate("SystemSpezificationDialog", "10"))
        self.la_minBatchSize.setText(_translate("SystemSpezificationDialog", "Minimum:"))
        self.le_minBatchSize.setText(_translate("SystemSpezificationDialog", "0"))
        self.la_maxBatchSize.setText(_translate("SystemSpezificationDialog", "Maximum:"))
        self.le_piBatchSize.setText(_translate("SystemSpezificationDialog", "0.9, 0.1"))
        self.la_liBatchSize.setText(_translate("SystemSpezificationDialog", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; font-size:14px; color:#222222; background-color:#ffffff;\">λ</span><span style=\" vertical-align:sub;\">i </span>:</p></body></html>"))
        self.le_liBatchSize.setText(_translate("SystemSpezificationDialog", "1, 20"))
        self.la_piBatchSize.setText(_translate("SystemSpezificationDialog", "<html><head/><body><p>p<span style=\" vertical-align:sub;\">i</span> :</p></body></html>"))
        self.la_transitionFunction.setText(_translate("SystemSpezificationDialog", "Transition Function"))
        self.la_batchSize.setText(_translate("SystemSpezificationDialog", "Service-Time:"))
        self.le_batchSize.setText(_translate("SystemSpezificationDialog", "1"))
        self.cb_serviceTimeAdjustment.setText(_translate("SystemSpezificationDialog", "Adjustment of Service-Time to Calculation Accuracy"))
        self.la_arrivalTimeDistributionFunction.setText(_translate("SystemSpezificationDialog", "Cumulative Arrival-Time Distribution Function:"))
        self.la_batchSizeDistributionFunction.setText(_translate("SystemSpezificationDialog", "Cumulative Batch-Size Distribution Function:"))
        self.tw_system.setTabText(self.tw_system.indexOf(self.qw_systemSpecificationDialog), _translate("SystemSpezificationDialog", "Queueing System"))

